spring:
  application:
    name: portfolio-tracker

  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio
    username: portfolio
    password: portfolio_local_dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug